name: Update DNS Records

on:
  push:
    branches:
      - main
    paths:
      - 'domains/*.json'

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Read domain files
        id: domains
        uses: javier-varez/read-json-action@v1
        with:
          path: domains/

      - name: Update DNS Records
        uses: cloudflare/wrangler-action@2.0.0
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          command: |
            for record in $(echo '${{ steps.domains.outputs.data }}' | jq -c '.records[]'); do
              type=$(echo $record | jq -r '.type')
              name=$(echo $record | jq -r '.name')
              content=$(echo $record | jq -r '.content')
              proxied=$(echo $record | jq -r '.proxied // true')
              
              wrangler dns-record put \
                --type=$type \
                --name=$name \
                --content=$content \
                --proxied=$proxied \
                --zone-id=$CLOUDFLARE_ZONE_ID
            done
