name: Update DNS Records

on:
  push:
    branches:
      - main
    paths:
      - 'domains/*.json'

jobs:
  update-dns:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Process DNS Records
        run: |
          for file in domains/*.json; do
            if [ -f "$file" ]; then
              records=$(jq -c '.records[]' "$file")
              echo "$records" | while IFS= read -r record; do
                type=$(echo "$record" | jq -r '.type')
                name=$(echo "$record" | jq -r '.name')
                content=$(echo "$record" | jq -r '.content')
                proxied=$(echo "$record" | jq -r '.proxied // true')
                
                echo "Processing record: $name ($type)"
                
                curl -X POST "https://api.cloudflare.com/client/v4/zones/${{ secrets.CLOUDFLARE_ZONE_ID }}/dns_records" \
                  -H "Authorization: Bearer ${{ secrets.CLOUDFLARE_API_TOKEN }}" \
                  -H "Content-Type: application/json" \
                  --data "{
                    \"type\": \"$type\",
                    \"name\": \"$name\",
                    \"content\": \"$content\",
                    \"proxied\": $proxied
                  }"
              done
            fi
          done
